(use-package elfeed
  :ensure t
  :pin melpa-stable
  :config
  (progn
    (setq elfeed-feeds '(("http://planet.clojure.in/atom.xml" clojure)
                         ("https://groups.google.com/forum/feed/clojure/msgs/atom.xml?num=50" clojure)
                         ("https://groups.google.com/forum/feed/clojurescript/msgs/atom.xml?num=50" clojurescript)
                         ("https://groups.google.com/forum/feed/cursive/msgs/atom.xml?num=50" clojure)
                         ("https://groups.google.com/forum/feed/clojure-java-jdbc/msgs/atom.xml?num=50" clojure)
                         ("https://www.reddit.com/r/Clojure/.rss" clojure)
                         ("https://www.reddit.com/r/Clojurescript/.rss" clojurescript)
                         ("http://insideclojure.org/feed.xml" clojure)
                         ("http://planet.emacsen.org/atom.xml" emacs)
                         ("https://groups.google.com/forum/feed/emacs-helm/msgs/atom.xml?num=50" emacs)
                         ("https://groups.google.com/forum/feed/emacsplus/msgs/atom.xml?num=50" emacs)
                         ("https://www.reddit.com/r/emacs/.rss" emacs)
                         ("http://planet.haskell.org/atom.xml" haskell)
                         ("https://groups.google.com/forum/feed/comp.lang.haskell/msgs/atom.xml?num=50" haskell)
                         ("https://www.reddit.com/r/haskell/.rss" haskell)
                         ("https://www.reddit.com/r/java/.rss" java)
                         ("https://www.reddit.com/r/javascript/.rss" java)
                         ("https://groups.google.com/forum/feed/purescript/msgs/atom.xml?num=50" purescript)
                         ("https://www.reddit.com/r/purescript/.rss" purescript)
                         ("https://www.reddit.com/r/scala/.rss" scala)
                         ("https://groups.google.com/forum/feed/qilang/msgs/atom.xml?num=50" shen)
                         ("http://www.nurkiewicz.com/atom.xml" misc)
                         ("http://degoes.net/feed.xml" misc)
                         ("https://steve-yegge.blogspot.com/atom.xml" misc)
                         ("https://groups.google.com/forum/feed/autokey-users/msgs/atom.xml?num=50" misc)
                         ("http://seancorfield.github.io/atom.xml" misc)
                         ("http://www.aaronsw.com/2002/feeds/pgessays.rss" misc)
                         ("http://blog.sigfpe.com/atom.xml" misc)
                         ("https://blog.plan99.net/feed" misc)
                         ("https://eax.me/feed/" misc)
                         ("https://juan-gandhi.dreamwidth.org/data/rss" misc)
                         ("https://deniok.dreamwidth.org/data/rss" misc)
                         ("http://esr.ibiblio.org/?feed=rss2" misc)))))
